# Generated by Django 5.0.4 on 2024-04-20 14:12

from django.db import migrations, models


def populate_plant(apps, schema_editor):
    Plant = apps.get_model('app', 'Plant')
    for i in range(10):
        plant = Plant(name=f'Plant {i+1}')
        plant.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),

        migrations.RunPython(
            code=populate_plant,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
